language: node_js
dist: trusty
addons:
  apt:
    packages:
    # This is required to run new chrome on old trusty
    - libnss3
cache: npm
install:
- npm install
before_script:
# Launch XVFB
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- npm run build
- npm run test
deploy:
  provider: script
  script: bash publish.sh
  on:
    branch: master

