language: node_js
dist: trusty
addons:
  apt:
    packages:
    # This is required to run new chrome on old trusty
    - libnss3
cache: npm
install:
- npm install
before_script:
# Launch XVFB
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
script:
- npm run build
- npm run test
deploy:
  provider: script
  script:
  - token="$(npx chrome-webstore-manager refresh_token --client_id ${CLIENT_ID} --client_secret ${CLIENT_SECRET} --refresh_token ${REFRESH_TOKEN})"
  - export WEBSTORE_TOKEN="${token}"
  - npx chrome-webstore-manager update gcgnjkmkkdllmfeeggghobokcnnfmjgg ./output/github-bugspots-extension.zip
  - npx chrome-webstore-manager publish gcgnjkmkkdllmfeeggghobokcnnfmjgg
  on:
    branch: master

